"""
Spec-Drafting Chatbot for skills2app

This chatbot guides non-technical users to create application specifications
based on skills generated by pdf2skills.
"""

from .spec_drafter import SpecDrafter, run_interactive
from . import prompts

__all__ = ["SpecDrafter", "run_interactive", "prompts"]
