#!/usr/bin/env python3
"""
Spec-Drafting Chatbot CLI

Run an interactive session to help users create application specifications
based on skills generated by pdf2skills.

Usage:
    python run_chatbot.py <router_path> [--output-dir <dir>] [--language <en|ch>]

Example:
    python run_chatbot.py ../test_data/book_output/full_chunks_skus/router.json
"""

import os
import sys
import argparse
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent))

from dotenv import load_dotenv

# Load .env
env_path = Path(__file__).parent / ".env"
load_dotenv(env_path)

from chatbot import run_interactive


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Spec-Drafting Chatbot - Guide users to create app specifications",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Run with router.json
  python run_chatbot.py ./router.json

  # Specify output directory for specs
  python run_chatbot.py ./router.json --output-dir ./my_specs

  # Set language (overrides .env)
  python run_chatbot.py ./router.json --language en
"""
    )

    parser.add_argument(
        "router_path",
        help="Path to router.json from pdf2skills"
    )
    parser.add_argument(
        "-o", "--output-dir",
        help="Directory to save generated specs (default: same as router.json)"
    )
    parser.add_argument(
        "-l", "--language",
        choices=["en", "ch", "English", "Chinese"],
        help="Output language (default: from .env)"
    )

    args = parser.parse_args()

    # Handle language override
    if args.language:
        lang = "English" if args.language in ["en", "English"] else "Chinese"
        os.environ["OUTPUT_LANGUAGE"] = lang

    router_path = Path(args.router_path)
    if not router_path.exists():
        print(f"Error: Router file not found: {router_path}")
        sys.exit(1)

    try:
        run_interactive(str(router_path), args.output_dir)
    except KeyboardInterrupt:
        print("\n\nInterrupted by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\nError: {e}")
        raise


if __name__ == "__main__":
    main()
